/**
 * Shared utility for generating printable PDF reports and sharing via WhatsApp/Email.
 * Uses browser print-to-PDF approach with styled HTML.
 */

const APP_NAME = "Check-iN";
const PRIMARY_COLOR = "hsl(213, 53%, 23%)";
const SUCCESS_COLOR = "hsl(160, 84%, 39%)";

interface ReportOptions {
  title: string;
  subtitle?: string;
  content: string; // markdown or plain text
  date?: string;
  category?: string;
}

/** Convert basic markdown to HTML (headings, bold, italic, lists, paragraphs) */
function markdownToHtml(md: string): string {
  return md
    .replace(/^### (.+)$/gm, '<h3 style="color:#1a365d;margin:16px 0 8px;font-size:15px;">$1</h3>')
    .replace(/^## (.+)$/gm, '<h2 style="color:#1a365d;margin:18px 0 8px;font-size:17px;">$1</h2>')
    .replace(/^# (.+)$/gm, '<h1 style="color:#1a365d;margin:20px 0 10px;font-size:20px;">$1</h1>')
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/^[•\-]\s+(.+)$/gm, '<li style="margin:2px 0;font-size:13px;">$1</li>')
    .replace(/(<li.*<\/li>\n?)+/g, (match) => `<ul style="margin:8px 0 8px 16px;padding:0;">${match}</ul>`)
    .replace(/^(?!<[hul])(.*\S.*)$/gm, '<p style="margin:6px 0;font-size:13px;line-height:1.6;">$1</p>')
    .replace(/⚠️/g, "⚠")
    .replace(/\n{2,}/g, "");
}

function buildHtml(opts: ReportOptions): string {
  const date = opts.date || new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" });
  const bodyHtml = markdownToHtml(opts.content);

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>${opts.title} — ${APP_NAME}</title>
<style>
  @media print {
    body { margin: 0; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    .no-print { display: none !important; }
  }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #1a202c; margin: 0; padding: 0; background: #fff; }
  .header { background: ${PRIMARY_COLOR}; color: #fff; padding: 24px 32px; }
  .header h1 { margin: 0 0 4px; font-size: 22px; font-weight: 700; }
  .header .subtitle { opacity: 0.85; font-size: 13px; margin: 0; }
  .header .meta { display: flex; gap: 16px; margin-top: 8px; font-size: 11px; opacity: 0.75; }
  .content { padding: 24px 32px 40px; max-width: 800px; }
  .category-badge { display: inline-block; background: ${SUCCESS_COLOR}; color: #fff; font-size: 11px; padding: 2px 10px; border-radius: 12px; margin-bottom: 12px; }
  .footer { border-top: 1px solid #e2e8f0; padding: 16px 32px; font-size: 10px; color: #a0aec0; text-align: center; }
  .disclaimer { background: #fff8e1; border-left: 3px solid #f6ad55; padding: 10px 14px; margin-top: 20px; font-size: 11px; color: #744210; border-radius: 4px; }
</style>
</head>
<body>
  <div class="header">
    <h1>${opts.title}</h1>
    ${opts.subtitle ? `<p class="subtitle">${opts.subtitle}</p>` : ""}
    <div class="meta">
      <span>📅 ${date}</span>
      <span>🏥 ${APP_NAME}</span>
    </div>
  </div>
  <div class="content">
    ${opts.category ? `<span class="category-badge">${opts.category}</span>` : ""}
    ${bodyHtml}
    <div class="disclaimer">⚠ This report is generated by AI for informational purposes only. Always consult a qualified healthcare professional for medical decisions.</div>
  </div>
  <div class="footer">Generated by ${APP_NAME} · ${date} · This document is confidential.</div>
</body>
</html>`;
}

export function printReport(opts: ReportOptions) {
  const html = buildHtml(opts);
  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(html);
  win.document.close();
  setTimeout(() => win.print(), 400);
}

export function shareViaWhatsApp(opts: ReportOptions) {
  const summary = `*${opts.title}*\n${APP_NAME}\n${opts.date || new Date().toLocaleDateString("en-IN")}\n\n${opts.content.substring(0, 1000)}${opts.content.length > 1000 ? "…" : ""}`;
  window.open(`https://wa.me/?text=${encodeURIComponent(summary)}`, "_blank");
}

export function shareViaEmail(opts: ReportOptions) {
  const subject = `${opts.title} — ${APP_NAME}`;
  const body = `${opts.title}\nDate: ${opts.date || new Date().toLocaleDateString("en-IN")}\n\n${opts.content}`;
  window.open(`mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`, "_self");
}
