import { useState, useEffect, useCallback } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Heart, Phone, Pill, Shield, User, AlertTriangle, Stethoscope, Printer, Share2, Loader2, Download } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import { buildLetterheadHtml } from "@/lib/reportPdf";

interface Props {
  wardUserId: string;
  wardName: string;
}

interface HealthData {
  blood_group: string | null;
  allergies: string[];
  chronic_conditions: string[];
  emergency_notes: string | null;
  family_doctor_name: string | null;
  family_doctor_phone: string | null;
}

interface MedView {
  name: string;
  dosage: string;
  frequency: string;
  schedule_times: string[];
}

interface MedicalHistoryEntry {
  type: string;
  reason: string;
  hospital_name: string | null;
  doctor_name: string | null;
  start_date: string | null;
  end_date: string | null;
  treatment: string | null;
}

interface GuardianView {
  guardian_name: string;
  guardian_phone: string;
  guardian_email: string | null;
  relation: string | null;
  is_primary: boolean;
}

const WardEmergencyCard = ({ wardUserId, wardName }: Props) => {
  const [health, setHealth] = useState<HealthData | null>(null);
  const [meds, setMeds] = useState<MedView[]>([]);
  const [guardians, setGuardians] = useState<GuardianView[]>([]);
  const [medicalHistory, setMedicalHistory] = useState<MedicalHistoryEntry[]>([]);
  const [profile, setProfile] = useState<{ date_of_birth: string | null; gender: string | null; phone: string | null; blood_group?: string | null } | null>(null);
  const [loading, setLoading] = useState(true);
  const [generatingPdf, setGeneratingPdf] = useState(false);

  const fetchData = useCallback(async () => {
    const [profileRes, healthRes, medsRes, guardiansRes, historyRes] = await Promise.all([
      supabase.from("profiles").select("date_of_birth, gender, phone").eq("id", wardUserId).maybeSingle(),
      supabase.from("health_profile").select("blood_group, allergies, chronic_conditions, emergency_notes, family_doctor_name, family_doctor_phone").eq("user_id", wardUserId).maybeSingle(),
      supabase.from("medications").select("name, dosage, frequency, schedule_times").eq("user_id", wardUserId),
      supabase.from("guardians").select("guardian_name, guardian_phone, guardian_email, relation, is_primary").eq("user_id", wardUserId),
      supabase.from("medical_history").select("type, reason, hospital_name, doctor_name, start_date, end_date, treatment").eq("user_id", wardUserId).order("start_date", { ascending: false }),
    ]);

    setProfile(profileRes.data);
    setHealth(healthRes.data ? {
      blood_group: healthRes.data.blood_group,
      allergies: (healthRes.data.allergies as string[]) || [],
      chronic_conditions: (healthRes.data.chronic_conditions as string[]) || [],
      emergency_notes: healthRes.data.emergency_notes,
      family_doctor_name: healthRes.data.family_doctor_name,
      family_doctor_phone: healthRes.data.family_doctor_phone,
    } : null);
    setMeds((medsRes.data || []) as MedView[]);
    setGuardians((guardiansRes.data || []) as GuardianView[]);
    setMedicalHistory((historyRes.data || []) as MedicalHistoryEntry[]);
    setLoading(false);
  }, [wardUserId]);

  useEffect(() => { fetchData(); }, [fetchData]);

  const buildShareText = () => {
    const lines = [
      `🚨 EMERGENCY HEALTH CARD — ${wardName}`,
      "",
      health?.blood_group ? `Blood Group: ${health.blood_group}` : "",
      profile?.date_of_birth ? `DOB: ${new Date(profile.date_of_birth).toLocaleDateString("en-IN")}` : "",
      profile?.phone ? `Phone: ${profile.phone}` : "",
      health?.allergies.length ? `⚠️ Allergies: ${health.allergies.join(", ")}` : "",
      health?.chronic_conditions.length ? `Conditions: ${health.chronic_conditions.join(", ")}` : "",
      meds.length ? `Medications: ${meds.map(m => `${m.name} (${m.dosage})`).join(", ")}` : "",
      health?.family_doctor_name ? `Doctor: ${health.family_doctor_name}${health.family_doctor_phone ? ` (${health.family_doctor_phone})` : ""}` : "",
      guardians.length ? `Emergency Contacts: ${guardians.map(g => `${g.guardian_name} ${g.guardian_phone}`).join(", ")}` : "",
      "",
      "Generated by Check-iN Emergency Response System",
    ];
    return lines.filter(Boolean).join("\n");
  };

  const handleShare = () => {
    const text = buildShareText();
    if (navigator.share) {
      navigator.share({ text }).catch(() => {});
    } else {
      navigator.clipboard.writeText(text);
      toast.success("Emergency card copied to clipboard");
    }
  };

  const buildEmergencyBodyHtml = () => {
    const h = health;
    return `
<div class="section"><div class="section-title">👤 Personal Information</div><div class="section-body">
<div class="row"><span class="label">Name</span><span class="value">${wardName}</span></div>
${profile?.date_of_birth ? `<div class="row"><span class="label">DOB</span><span class="value">${new Date(profile.date_of_birth).toLocaleDateString("en-IN")}</span></div>` : ""}
${profile?.gender ? `<div class="row"><span class="label">Gender</span><span class="value" style="text-transform:capitalize">${profile.gender}</span></div>` : ""}
${profile?.phone ? `<div class="row"><span class="label">Phone</span><span class="value">${profile.phone}</span></div>` : ""}
${h?.blood_group ? `<div class="row"><span class="label">Blood Group</span><span class="value"><span class="badge">${h.blood_group}</span></span></div>` : ""}
</div></div>
${h?.allergies.length ? `<div class="alert-box"><p>⚠️ ALLERGIES: ${h.allergies.map(a => `<span class="badge">${a}</span>`).join(" ")}</p></div>` : ""}
${h?.chronic_conditions.length ? `<div class="section"><div class="section-title">🩺 Medical Conditions</div><div class="section-body">${h.chronic_conditions.map(c => `<span class="badge" style="background:#eff6ff;color:#2563eb">${c}</span>`).join(" ")}</div></div>` : ""}
${meds.length ? `<div class="section"><div class="section-title">💊 Medications</div><div class="section-body"><table><tr><th>Medication</th><th>Dosage</th><th>Frequency</th><th>Times</th></tr>${meds.map(m => `<tr><td>${m.name}</td><td>${m.dosage}</td><td>${m.frequency.replace(/_/g," ")}</td><td>${(m.schedule_times||[]).join(", ")}</td></tr>`).join("")}</table></div></div>` : ""}
${h?.emergency_notes ? `<div class="section"><div class="section-title">📝 Emergency Notes</div><div class="section-body"><p>${h.emergency_notes}</p></div></div>` : ""}
${h?.family_doctor_name ? `<div class="section"><div class="section-title">👨‍⚕️ Family Doctor</div><div class="section-body"><div class="row"><span class="label">Name</span><span class="value">${h.family_doctor_name}</span></div>${h.family_doctor_phone ? `<div class="row"><span class="label">Phone</span><span class="value">${h.family_doctor_phone}</span></div>` : ""}</div></div>` : ""}
${guardians.length ? `<div class="section"><div class="section-title">🛡️ Emergency Contacts</div><div class="section-body"><table><tr><th>Name</th><th>Relation</th><th>Phone</th></tr>${guardians.map(g => `<tr><td>${g.guardian_name}${g.is_primary ? " ⭐" : ""}</td><td>${g.relation || "—"}</td><td>${g.guardian_phone}</td></tr>`).join("")}</table></div></div>` : ""}`;
  };

  const handlePrint = () => {
    setGeneratingPdf(true);
    try {
      const html = buildLetterheadHtml({
        title: "EMERGENCY HEALTH CARD",
        subtitle: wardName,
        bodyHtml: buildEmergencyBodyHtml(),
      });
      const w = window.open("", "_blank");
      if (!w) { toast.error("Pop-up blocked"); return; }
      w.document.write(html);
      w.document.close();
      setTimeout(() => w.print(), 300);
      toast.success("Emergency card opened for printing");
    } finally {
      setGeneratingPdf(false);
    }
  };

  const handleDownload = () => {
    const html = buildLetterheadHtml({
      title: "EMERGENCY HEALTH CARD",
      subtitle: wardName,
      bodyHtml: buildEmergencyBodyHtml(),
    });
    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `Emergency-Health-Card-${wardName.replace(/\s+/g, "-")}.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success("Emergency card downloaded");
  };

  if (loading) return null;
  if (!health && !profile) return null;

  return (
    <Card>
      <CardHeader className="pb-2">
        <CardTitle className="text-lg flex items-center gap-2">
          <Heart className="w-5 h-5 text-destructive" />
          Emergency Health Card
        </CardTitle>
        <p className="text-xs text-muted-foreground">{wardName}'s critical health information</p>
      </CardHeader>
      <CardContent className="space-y-3">
        {/* Blood Group & Basic Info */}
        <div className="flex items-center gap-3 flex-wrap">
          {health?.blood_group && (
            <Badge variant="destructive" className="text-sm px-3 py-1">{health.blood_group}</Badge>
          )}
          {profile?.date_of_birth && (
            <span className="text-xs text-muted-foreground">DOB: {new Date(profile.date_of_birth).toLocaleDateString("en-IN")}</span>
          )}
          {profile?.phone && (
            <span className="text-xs text-muted-foreground">📞 {profile.phone}</span>
          )}
        </div>

        {/* Allergies */}
        {health?.allergies && health.allergies.length > 0 && (
          <div className="p-3 rounded-lg bg-destructive/5 border border-destructive/20">
            <div className="flex items-center gap-1 mb-1">
              <AlertTriangle className="w-4 h-4 text-destructive" />
              <span className="text-xs font-bold text-destructive">ALLERGIES</span>
            </div>
            <div className="flex flex-wrap gap-1">
              {health.allergies.map((a, i) => <Badge key={i} variant="destructive" className="text-xs">{a}</Badge>)}
            </div>
          </div>
        )}

        {/* Medical Conditions */}
        {health?.chronic_conditions && health.chronic_conditions.length > 0 && (
          <div>
            <p className="text-xs text-muted-foreground mb-1">Medical Conditions</p>
            <div className="flex flex-wrap gap-1">
              {health.chronic_conditions.map((c, i) => <Badge key={i} variant="secondary" className="text-xs">{c}</Badge>)}
            </div>
          </div>
        )}

        {/* Medications */}
        {meds.length > 0 && (
          <div>
            <p className="text-xs text-muted-foreground mb-1 flex items-center gap-1"><Pill className="w-3 h-3" /> Medications</p>
            {meds.map((m, i) => (
              <div key={i} className="flex items-center justify-between py-1 border-b border-border last:border-0">
                <span className="text-sm font-medium">{m.name}</span>
                <span className="text-xs text-muted-foreground">{m.dosage}</span>
              </div>
            ))}
          </div>
        )}

        {/* Family Doctor */}
        {health?.family_doctor_name && (
          <div className="flex items-center gap-2 text-sm">
            <Stethoscope className="w-4 h-4 text-primary" />
            <span>{health.family_doctor_name}</span>
            {health.family_doctor_phone && <span className="text-muted-foreground">({health.family_doctor_phone})</span>}
          </div>
        )}

        {/* Emergency Notes */}
        {health?.emergency_notes && (
          <p className="text-xs text-muted-foreground italic">📝 {health.emergency_notes}</p>
        )}

        {/* Actions */}
        <div className="flex gap-2 pt-1">
          <Button onClick={handleShare} variant="outline" size="sm" className="flex-1">
            <Share2 className="w-4 h-4 mr-1" /> Share
          </Button>
          <Button onClick={handlePrint} disabled={generatingPdf} variant="outline" size="sm" className="flex-1">
            {generatingPdf ? <Loader2 className="w-4 h-4 mr-1 animate-spin" /> : <Printer className="w-4 h-4 mr-1" />}
            Print
          </Button>
          <Button onClick={handleDownload} variant="outline" size="sm" className="flex-1">
            <Download className="w-4 h-4 mr-1" /> Save
          </Button>
        </div>
      </CardContent>
    </Card>
  );
};

export default WardEmergencyCard;
